[project]
name = "orgpedia-mahwom2024"
version = "0.0.1"
description = "Datapackage containing orders of Women and Child Development Department Government of Maharashtra."
authors = [{ name = "Orgpedia Foundation", email = "orgpedia.foundation@gmail.com" }]
requires-python = ">=3.10"
readme = "README.md"
license = "MIT"
keywords = [
    "information extraction",
    "data package",
    "government data",
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Information Analysis",
]

[project.urls]
homepage = "https://www.orgpedia.in/"
repository = "https://github.com/orgpedia/mahwom2024"
"data issues" = "https://github.com/orgpedia/mahwom2024/discussions"

[dependency-groups]
dev = [
    "pdfplumber>=0.9.0,<0.10",
    "requests>=2.31.0,<3",
    "pytesseract>=0.3.10,<0.4",
    "docint",
    "ruff>=0.2.2,<0.3",
    "pre-commit>=2.21.0,<3",
    "translateindic",
    "orgpedia",
]

[tool.uv.sources]
docint = { git = "https://github.com/mukundesh/docInt.git" }
translateindic = { git = "https://github.com/orgpedia/translateIndic" }
orgpedia = { git = "https://github.com/orgpedia/orgpedia.git" }

[tool.hatch.build.targets.sdist]
include = [
    "export/orgpedia_mahwom2024",
    "export/orgpedia_mahwom2024/*",
]

[tool.hatch.build.targets.wheel]
include = [
    "export/orgpedia_mahwom2024",
    "export/orgpedia_mahwom2024/*",
]

[tool.hatch.build.targets.wheel.sources]
"export/orgpedia_mahwom2024" = "orgpedia_mahwom2024"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
# Enable Pyflakes `E` and `F` codes by default.
lint.select = ["E", "F", "W", "I001"]
lint.ignore = []

# Allow autofix for all enabled rules (when `--fix`) is provided.
lint.fixable = ["I001"] # fix only isort issues
lint.unfixable = []
lint.per-file-ignores = {}

# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".mypy_cache",
    ".nox",
    ".ruff_cache",
    ".tox",
    "__pypackages__",
    "dist",
    "node_modules",
    "venv",
    ".bak",
    "input",
    "output",
    "logs",
    "conf",
    "export",
    "models",
    "documents",
    "data_packages",
    "websites",
    "page_images",
    "html",
]

# Same as Black.
line-length = 100

# Allow unused variables when underscore-prefixed.
#dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

target-version = "py310"
